#!/bin/bash


# setup vars
source /home/arkadyt/code/private/env/wwnet/db.env
export MONGO_INITDB_ROOT_USERNAME MONGO_INITDB_ROOT_PASSWORD
MONGO_URI="mongodb://$MONGO_INITDB_ROOT_USERNAME:$MONGO_INITDB_ROOT_PASSWORD@localhost:27019/socnet"


# restore
echo ::: restoring socnet.arkadyt.com\'s database from backup... :::
mongorestore \
  --drop \
  --preserveUUID \
  --uri=$MONGO_URI \
  /home/arkadyt/code/dotfiles/cloud/dbrestore/socnet
