#!/bin/bash

# wipeout
echo ::: purging socnet database... :::
mongo \
  --eval "db.getCollectionNames().forEach(function(n){db[n].remove({})});" \
  localhost:27017/socnet

echo ::: sleeping 60 seconds... :::
sleep 60

# restore
echo ::: restoring socnet database from backup... :::
mongorestore \
  -d socnet \
  /home/arkadyt/code/dotfiles/cloud/dbrestore/socnet
