#!/bin/bash

DATE=`date +%d-%m-%Y_%H.%M.%S`

echo copying to hard drive...
rclone copyto ~/Documents/Passwords.kdbx /media/arkadyt/arcan770077f/Cloud/MISC/Passwords/Passwords_$DATE.kdbx -v

echo copying to gdr...
rclone copyto ~/Documents/Passwords.kdbx gdr:HDrive/MISC/Passwords/Passwords_$DATE.kbdx -v

echo copying to gdr_lena...
rclone copyto ~/Documents/Passwords.kdbx gdr_lena:Passwords_$DATE.kdbx -v
